### ISSUE TITLE
Update the required rust version from 1.65.0 to 1.70.0

### ISSUE THREAD

**Issue by seroze** [paradigmxyz/reth#2997]
### Describe the change

Latest reth code base(on June 6, 2023) is failing to build with rust 1.65.0 so let's update this to 1.70.0 accordingly on the main page. 

Error trace:
```  error[E0658]: use of unstable library feature 'is_some_and'
  --> crates/storage/provider/src/providers/state/historical.rs:57:45
   |
57 |             if rank == 0 && !cursor.prev()?.is_some_and(|(key, _)| key.key == address) {
   |                                             ^^^^^^^^^^^
   |
   = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information

error[E0658]: use of unstable library feature 'is_some_and'
  --> crates/storage/provider/src/providers/state/historical.rs:88:33
   |
88 |                 !cursor.prev()?.is_some_and(|(key, _)| {
   |                                 ^^^^^^^^^^^
   |
   = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `reth-provider` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by mattsse** [comment]
I think we only state it in the readme

do you want to update this?
