### PR TITLE
fix: add revm-state to dev-dependencies of chain-state crate

### PR DESCRIPTION
**Pull request by futreall**
Running the following command fails with compilation error:

cargo test -p reth-chain-state

```bash
error[E0432]: unresolved import `revm_state`
  --> crates/chain-state/src/test_utils.rs:28:5
   |
28 | use revm_state::AccountInfo;
   |     ^^^^^^^^^^ use of unresolved module or unlinked crate `revm_state`
```

This is a regression from commit 336c3d1fa (#14021) which migrated from `revm` to `revm-state`. The migration correctly:
- Updated dependencies: `revm` → `revm-database` + `revm-state = { optional = true }`
- Updated features: added `"revm-state"` to test-utils

But it accidentally removed `revm.workspace = true` from dev-dependencies without replacing it with `revm-state.workspace = true`. Add `revm-state.workspace = true` to dev-dependencies, following the pattern used in other crates like `reth-provider`, `reth-trie`, and `reth-primitives-traits`.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
makes sense
