### ISSUE TITLE
support for FreeBSD

### ISSUE THREAD

**Issue by yangl1996** [paradigmxyz/reth#4259]
### Describe the feature

Reth currently does not compile on FreeBSD (13.2). The rust toolchain I used was 1.70.0. Cause of compilation error (at least the first one that pops up when `cargo build`) is that the `metrics-process` library does not implement metric collector for FreeBSD. I was wondering if the metrics subsystem can be disabled at compilation time (and the dependency disabled), so that at least the core functionalities of Reth can run on FreeBSD.

(submitting the ticket because I do not find any other discussion re. freebsd in the issues list; please let me know if it is not the correct place to discuss this issue)

**Comment by yangl1996** [comment]
Okay I was able to compile Reth on FreeBSD with the following tweaks. I'm not sure if any of them is unnecessary, and will do a bisection to figure out. But for now here's what I did:

1. Silent the compilation error of `metrics-process` with the following patch. It's not really a fix in the sense that the library won't provide metrics on FreeBSD (it's just an empty implementation), but at least it compiles. It does not seem hard to add real support for FreeBSD either. 
```
diff --git a/src/collector.rs b/src/collector.rs
index 3b47870..3fd11d2 100644
--- a/src/collector.rs
+++ b/src/collector.rs
@@ -8,6 +8,9 @@ mod linux;
 #[path = "collector/windows.rs"]
 mod win;
 
+#[cfg(target_os = "freebsd")]
+mod freebsd;
+
 /// Process metrics
 /// https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics
 #[derive(Debug, Default, PartialEq)]
@@ -41,6 +44,9 @@ pub use linux::collect;
 #[cfg(target_os = "windows")]
 pub use win::collect;
 
+#[cfg(target_os = "freebsd")]
+pub use freebsd::collect;
+
 #[cfg(test)]
 mod tests {
     use super::*;
```
2. After the previous step, all dependencies should compile. But when compiling the `reth` binary itself, linker will complain that it cannot find `__cpu_model` and another symbol. The two missing symbols come from libgcc, so I needed to install it (`pkg install gcc12-devel`).
3. Somehow rust won't try to link with libgcc, so I needed to add `println!("cargo:rustc-link-lib=static=gcc");` to `bin/reth/build.rs`.
4. Rust will now complain that it cannot find libgcc, so I added `linker = "gcc12"` to `.cargo/config`, and set `RUSTFLAGS="-L/usr/lib"` when calling cargo.

I'm happy to prepare a PR for these changes if the Reth team deems support for FreeBSD valuable.
